### ISSUE TITLE
(NaN * earth radius)

### ISSUE THREAD

**Issue by Cjgraetz** [codementum/exoplanets#1]
The times earth radius counter always shows (NaN \* earth radius). refresh did nott change issue.
occured on every planet.
image of issue attached

![exo bug](https://cloud.githubusercontent.com/assets/20855110/17430203/0e32c638-5b32-11e6-87e7-6e9c68ccc995.PNG)

EDIT: issue stops when switched between color by disatance to nearest star and size. resumes on refresh.

**Comment by codementum** [comment]
Fixed in https://github.com/codementum/exoplanets/commit/d11234b3041f36115fefa1502432066a6802a9e4

Thanks!!
